[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

# Remappings for npm packages
remappings = ["@layerzerolabs/oft-evm/=node_modules/@layerzerolabs/oft-evm/", "@layerzerolabs/oft-evm-upgradeable/=node_modules/@layerzerolabs/oft-evm-upgradeable/", "@layerzerolabs/oapp-evm/=node_modules/@layerzerolabs/oapp-evm/", "@layerzerolabs/oapp-evm-upgradeable/=node_modules/@layerzerolabs/oapp-evm-upgradeable/", "@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/", "@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/", "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/", "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
optimizer = true
optimizer_runs = 1000
via_ir = true
